// pages/Tipps & Tricks/anleitungen/tunika.vue
<template>
  <div>
    <Intro small>
      <h2 class="mb-5">Die Tunika</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          <p>
            Die Tunika ist das klassische Gewand zu der Zeit. Weitere Infos z.B.
            auf
            <a
              target="_blank"
              href="http://www.die-roemer-online.de/militaer/ausruestung/tunica.html"
              >die Römer Online</a
            >. Allgemeinhin galt es als unhöflich, seine Tunika ohne Gürtel zu
            tragen. Anscheinend war es eine Bestrafung für Soldaten, wenn sie
            ihren Wachdienst ohne ihren Gürtel verrichten mussten.
          </p>
          <p>
            Da eine Tunika sehr einfach selbst zu nähen ist, haben wir hierfür
            gleich mehrere Anleitungen. Das lohnt sich besonders, denn es ist
            generell sinnvoll, mehr als eine Tunika zu haben. So hat man eine
            Ersatztunika, die man verwenden kann, wenn die eine dreckig ist.
            Außerdem weiß man, dass es üblich war, mehrere Tuniken übereinander
            zu ziehen, insbesondere da Leinen deutlich angenehmer auf der Haut
            ist als Wolle.
          </p>
          <p>
            Gerade bei Darstellungen im Frühling und Winter ist eine wollene
            Tunika sehr sinnvoll. Gerade nördlich der Alpen ist auch davon aus
            zu gehen, dass in der kalten Jahreszeit auch langärmlige Tunika
            getragen wurden.
          </p>
          <p>
            Es gibt Diskussion darüber, wie weit und entsprechend Falten werfend
            Tuniken wirklich waren. Da die meisten Darstellungen in Stein
            gehauen sind, ist es durchaus denkbar, dass die Steinmetze mit immer
            atemberaubenderen Darstellungen von wallendem Stoff ihre Finesse
            unter beweis stellen wollten. Eine insbesondere im Schritt weite
            Tunika erlaubt aber natürlich bessere Bewegungsfreiheit.
          </p>
        </b-col>
      </b-row>
    </Intro>

    <Section title="Anfertigen von Tuniken">
      <h3 class="h4 mt-4">1. Variante</h3>
      <b-img
        alt="Nicos Anleitung für Tuniken"
        :src="require('assets/anleitungen/nicos_tunic.jpg')"
        fluid
      />

      <h3 class="h4 mt-4">2. Variante</h3>
      <p>
        Man kann eine Tunika mit weniger Nähaufwand erstellen, wenn man ein
        langes Stück Leinen nimmt, was wie ein Poncho zusammen gelegt wird. Der
        Stoff muss dabei so lang sein, dass er zwei Mal die Distanz von den
        Schultern zum Knie (plus Puffer) hat. Die Ärmel sind dabei Teil vom
        Stoff, sodass man die Form eines Plus erhält. So muss man nur die Ärmel
        unten und den Korpus an der Seite zu nähen, die Ärmel und den Bund unten
        umnähen und einen Schlitz (größer 30cm) oben als Ausschnitt schneiden
        und versäumen.
      </p>
    </Section>
  </div>
</template>

<script>
import Intro from '~/components/intro'
import Section from '~/components/section'

export default {
  name: 'Tunika',
  components: { Intro, Section }
}
</script>

<style scoped></style>

// src/app/anleitungen/tunika/page.tsx
import { PageIntro } from "@/components/PageIntro/PageIntro";
import { Section } from "@/components/Section/Section";
import { AnleitungsBild } from "@/components/AnleitungsBild/AnleitungsBild";
import Tunika from "@/images/anleitungen/nicos_tunic.jpg";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "IG Romanum - Anleitung Tunika",
  description:
    "Hintergrundinformationen und Nähanleitung für die römische Tunika.",
  keywords: [
    "Tunika",
    "Römer",
    "Reenactment",
    "Kleidung",
    "IG Romanum",
    "Anleitung",
    "Nähen",
    "Ausrüstung",
  ],
  authors: [{ name: "IG Romanum" }],
  openGraph: {
    title: "IG Romanum - Anleitung Tunika",
    description:
      "Hintergrundinformationen und Nähanleitung für die römische Tunika.",
    images: ["/images/banner.jpg"],
    type: "article",
    url: "https://www.ig-romanum.de/anleitungen/tunika",
  },
  twitter: {
    card: "summary_large_image",
    title: "IG Romanum - Anleitung Tunika",
    description:
      "Hintergrundinformationen und Nähanleitung für die römische Tunika.",
    images: ["/images/banner.jpg"],
  },
  robots: "index, follow",
  alternates: {
    canonical: "https://www.ig-romanum.de/anleitungen/tunika",
  },
};

const TunikaPage = () => (
  <>
    <PageIntro
      img={`/AnleitungsBilder/tunika.jpg`}
      imgAlt="Zeichnerische Darstellung eines römischen Tunika"
    >
      <h2 className="mb-5">Die Tunika</h2>
      <div className="row mb-4">
        <div className="col-md-10 offset-md-1">
          <p>
            Die Tunika ist das klassische Gewand zu der Zeit. Weitere Infos z.B.
            auf{" "}
            <a
              target="_blank"
              href="http://www.die-roemer-online.de/militaer/ausruestung/tunica.html"
            >
              die Römer Online
            </a>
            . Allgemeinhin galt es als unhöflich, seine Tunika ohne Gürtel zu
            tragen. Anscheinend war es eine Bestrafung für Soldaten, wenn sie
            ihren Wachdienst ohne ihren Gürtel verrichten mussten.
          </p>
          <p>
            Da eine Tunika sehr einfach selbst zu nähen ist, haben wir hierfür
            gleich mehrere Anleitungen. Das lohnt sich besonders, denn es ist
            generell sinnvoll, mehr als eine Tunika zu haben. So hat man eine
            Ersatztunika, die man verwenden kann, wenn die eine dreckig ist.
            Außerdem weiß man, dass es üblich war, mehrere Tuniken übereinander
            zu ziehen, insbesondere da Leinen deutlich angenehmer auf der Haut
            ist als Wolle.
          </p>
          <p>
            Gerade bei Darstellungen im Frühling und Winter ist eine wollene
            Tunika sehr sinnvoll. Gerade nördlich der Alpen ist auch davon aus
            zu gehen, dass in der kalten Jahreszeit auch langärmlige Tunika
            getragen wurden.
          </p>
          <p>
            Es gibt Diskussion darüber, wie weit und entsprechend Falten werfend
            Tuniken wirklich waren. Da die meisten Darstellungen in Stein
            gehauen sind, ist es durchaus denkbar, dass die Steinmetze mit immer
            atemberaubenderen Darstellungen von wallendem Stoff ihre Finesse
            unter beweis stellen wollten. Eine insbesondere im Schritt weite
            Tunika erlaubt aber natürlich bessere Bewegungsfreiheit.
          </p>
        </div>
      </div>
    </PageIntro>

    <Section title="Anfertigen von Tuniken">
      <h3 className="h4 mt-4">1. Variante</h3>
      <AnleitungsBild src={Tunika} alt="Nicos Anleitung für Tuniken" />

      <h3 className="h4 mt-4">2. Variante</h3>
      <p>
        Man kann eine Tunika mit weniger Nähaufwand erstellen, wenn man ein
        langes Stück Leinen nimmt, was wie ein Poncho zusammen gelegt wird. Der
        Stoff muss dabei so lang sein, dass er zwei Mal die Distanz von den
        Schultern zum Knie (plus Puffer) hat. Die Ärmel sind dabei Teil vom
        Stoff, sodass man die Form eines Plus erhält. So muss man nur die Ärmel
        unten und den Korpus an der Seite zu nähen, die Ärmel und den Bund unten
        umnähen und einen Schlitz (größer 30cm) oben als Ausschnitt schneiden
        und versäumen.
      </p>
    </Section>
  </>
);

export default TunikaPage;
