// src/pages/mitglieder.tsx
import { PageIntro } from "@/components/PageIntro/PageIntro";
import type { Member } from "@/components/Members/types";

import Banner from "@/images/banner/banner_mitglieder.jpg";
import Andre from "@/images/mitglieder/Andre.jpg";
import Fabian from "@/images/mitglieder/Fabian.jpg";
import Franzi from "@/images/mitglieder/Franzi.jpg";
import Kristin from "@/images/mitglieder/Kristin.jpg";
import Lars from "@/images/mitglieder/Lars.jpg";
import Manu from "@/images/mitglieder/Manu.jpg";
import Max from "@/images/mitglieder/Max.jpg";
import Nico from "@/images/mitglieder/Nico.jpg";
import Nina from "@/images/mitglieder/Nina.jpg";
import Thomas from "@/images/mitglieder/Thomas.jpg";
import { Members } from "@/components/Members/Members";

const membersRaw = [
  {
    img: Nico,
    name: "Optio Nicos",
    text: 'Nach dem "überraschenden" Ableben des Zenturios vorläufiger Kopf der Truppe. Man munkelt er versteckt mittels dem Helmbusch eine alte Kriegsnarbe.',
  },
  {
    img: Lars,
    name: "Vexillifer Larsos",
    text: "Er schwört darauf das Vexillium in der Not so rabiat zu verteidigen wie seinen Ruf als Frauenschwarm.",
  },
  {
    img: Fabian,
    name: "Tesserarius Fabius",
    text: "Behauptungen nach ist er der einzige der Truppe, der schreiben kann. Zufällig muss dringend etwas geschrieben werden, wenn es harte Arbeit gibt...",
  },
  {
    img: Kristin,
    name: "Rhamis, Tochter eines Chatten",
    text: "Verschleppt nach Rom, konnte sie entkommen und schloss sich zu ihrem eigenen Schutz dieser Gruppe Legionären an um wieder in ihre Heimat zu gelangen.",
  },
  {
    img: Thomas,
    name: "Legionär Thomasus",
    text: "Erzählt gerne Geschichten über die Siege seiner Legion, auch wenn die Meisten davon freilich erfunden sind.",
  },
  {
    img: Nina,
    name: "Bürgerin Nina",
    text: "Kameraden erzählen sich, sie habe ein Warn-Mosaik eines Hundes vor ihrem Hof, das an Größe nur durch das Tier selbst übertroffen wird.",
  },
  {
    img: Manu,
    name: "Legionär Manus",
    text: 'Sprichwörtlich die rechte Hand des Optios wenn es Aufgaben besonderer "Präzision" geht.',
  },
  {
    img: Franzi,
    name: "Griechin Franzisca",
    text: "Bediente als Freigelassene Schankwirtin in der Nähe des Kastells indem sich Legionär Manus befand, der sie oft aufsuchte.",
  },
  {
    img: Andre,
    name: "Auxiliar Andreus",
    text: "Ist als Kind in einen Kessel voller Mulsum gefallen, und lehrt seitdem die Barbaren das Fürchten.",
  },
  {
    img: Max,
    name: "Legionär Maxentius",
    text: "Gnade den Barbaren, wenn Sie die Mulsumlieferung überfallen.",
  },
];
const groups: Array<Array<Member>> = [];
const times = Math.ceil(membersRaw.length / 3);
for (let i = 0; i <= times; i++) {
  groups.push(membersRaw.splice(0, 3));
}

const mitglieder = () => (
  <>
    <PageIntro img={Banner}>
      <h2 className="mb-5">Unsere Mitglieder</h2>
      <div className="row mb-4">
        <div className="col col-md-10 offset-md-1">
          <p>
            Hier sind alle aufgelistet, die momentan in der IG Imperium Romanum
            aktiv sind.
          </p>
          <p>
            Auch wenn die Liste aktuell viele Soldaten enthält, so freuen wir
            uns doch, wenn wir bald hoffentlich mehr der Zivilbevölkerung
            darstellen können.
          </p>
          <p>
            Wir wollen uns besonders bei{" "}
            <a target="_blank" href="https://www.instagram.com/pictrail_de">
              Christine Lincke
            </a>{" "}
            bedanken, die für uns die meisten der hier zu sehenden Portraits
            aufgenommen hat.
          </p>
        </div>
      </div>
    </PageIntro>

    <Members memberGroups={groups} />
  </>
);

export default mitglieder;

// pages/mitglieder/index.vue
<template>
  <div>
    <Intro small :image-url="require('~/assets/banner/banner_mitglieder.jpg')">
      <h2 class="mb-5">Unsere Mitglieder</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          <p>
            Hier sind alle aufgelistet, die momentan in der IG Imperium Romanum
            aktiv sind.
          </p>
          <p>
            Auch wenn die Liste aktuell viele Soldaten enthält, so freuen wir
            uns doch, wenn wir bald hoffentlich mehr der Zivilbevölkerung
            darstellen können.
          </p>
          <p>
            Wir wollen uns besonders bei <a target="_blank" href="https://www.instagram.com/pictrail_de">Christine Lincke</a> bedanken,
            die für uns die meisten der hier zu sehenden Portraits aufgenommen hat.
          </p>
        </b-col>
      </b-row>
    </Intro>

    <div
      v-for="(memberGroup, index) in memberGroups"
      :key="index"
      class="ig-mosaic"
    >
      <b-container
        ><b-row>
          <b-col
            v-for="(member, idx) in memberGroup"
            :key="idx"
            cols="12"
            md="4"
            class="mb-3"
          >
            <div class="ig-border-box d-flex justify-content-center">
              <h3 class="mb-0 align-self-center">{{ member.name }}</h3>
            </div>
            <div class="ig-spacing">
              <div class="ig-img-overflow">
                <b-img
                  fluid
                  :src="require(`assets/mitglieder/${member.img}.jpg`)"
                />
              </div>
              <p class="mt-3">{{ member.text }}</p>
            </div>
          </b-col>
        </b-row></b-container
      >
    </div>
  </div>
</template>

<script>
import Intro from '~/components/intro'

export default {
  name: 'IndexVue',
  components: { Intro },
  data: () => ({
    membersRaw: [
      {
        img: 'Nico',
        name: 'Optio Nicos',
        text:
          'Nach dem "überraschenden" Ableben des Zenturios vorläufiger Kopf der Truppe. Man munkelt er versteckt mittels dem Helmbusch eine alte Kriegsnarbe.'
      },
      {
        img: 'Lars',
        name: 'Vexillifer Larsos',
        text:
          'Er schwört darauf das Vexillium in der Not so rabiat zu verteidigen wie seinen Ruf als Frauenschwarm.'
      },
      {
        img: 'Fabian',
        name: 'Tesserarius Fabius',
        text:
          'Behauptungen nach ist er der einzige der Truppe, der schreiben kann. Zufällig muss dringend etwas geschrieben werden, wenn es harte Arbeit gibt...'
      },
      {
        img: 'Kristin',
        name: 'Bürgerin Kristina',
        text:
          'Man sagt sie war eine angesehene römische Bürgerin, bis sie sich scheinbar in einen prahlerischen Legionär verguckte.'
      },
      {
        img: 'Thomas',
        name: 'Legionär Thomasus',
        text:
          'Erzählt gerne Geschichten über die Siege seiner Legion, auch wenn die Meisten davon freilich erfunden sind.'
      },
      {
        img: 'Nina',
        name: 'Bürgerin Nina',
        text:
          'Kameraden erzählen sich sie habe ein Warn-Mosaik eines Hundes vor ihrem Hof, das an Größe nur durch das Tier selbst übertroffen wird.'
      },
      {
        img: 'Manu',
        name: 'Legionär Manus',
        text:
          'Sprichwörtlich die rechte Hand des Optios wenn es Aufgaben besonderer "Präzision" geht.'
      },
      {
        img: 'Franzi',
        name: 'Griechin Franzisca',
        text:
          'Bediente als Freigelassene Schankwirtin in der Nähe des Kastells indem sich Legionär Manus befand, der sie oft aufsuchte.'
      },
      {
        img: 'Andre',
        name: 'Auxiliar Andreus',
        text:
          'Ist als Kind in einen Kessel voller Mulsum gefallen, und lehrt seitdem die Barbaren das Fürchten.'
      },
      {
        img: 'Max',
        name: 'Legionär Maxentius',
        text: 'Gnade den Barbaren, wenn Sie die Mulsumlieferung überfallen.'
      }
    ]
  }),
  computed: {
    memberGroups() {
      const members = [].concat(this.membersRaw)
      const groups = []
      const times = Math.ceil(members.length / 3)
      for (let i = 0; i <= times; i++) {
        groups.push(members.splice(0, 3))
      }
      return groups
    }
  },
  head() {
    return {
      title: 'Mitglieder',
      meta: [
        {
          hid: 'ogTitle',
          property: 'og:title',
          content: 'Mitglieder der IG Romanum'
        }
      ]
    }
  }
}
</script>

<style lang="scss" scoped>
.ig-mosaic {
  background-image: url('~assets/mosaik.jpg');
  background-size: auto 60px;
  background-position: left top;
  background-repeat: repeat-x;

  .ig-border-box {
    text-align: center;
    height: 60px;
    h3 {
      font-size: 1.4rem;
    }
  }
  .ig-spacing {
    margin: 0 5px;
    .ig-img-overflow {
      max-height: 520px;
      overflow: hidden;
    }
  }
}
</style>
