// src/pages/anleitungen/index.tsx
import { PageIntro } from "@/components/PageIntro/PageIntro";
import { AnleitungsVerzeichnis } from "@/components/AnleitungsVerzeichnis";

import Banner from "@/images/banner.jpg";

const Anleitungen = () => {
  return (
    <>
      <PageIntro img={Banner}>
        <h2 className="mb-4 pb-4">Anleitungen</h2>
        <div className="row mb-4">
          <div className="col-md-10 offset-md-1">
            Hier sind all unsere Anleitungen aufgelistet.
          </div>
        </div>
      </PageIntro>
      <AnleitungsVerzeichnis />
    </>
  );
};

export default Anleitungen;

// pages/Tipps & Tricks/anleitungen/index.vue
<template>
  <div>
    <Intro small>
      <h2 class="mb-5">Anleitungen</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          Hier sind all unsere Anleitungen aufgelistet.
        </b-col>
      </b-row>
    </Intro>
    <AnleitunsVerzeichnis />
  </div>
</template>

<script>
import AnleitunsVerzeichnis from '~/components/AnleitunsVerzeichnis'
import Intro from '~/components/intro'

export default {
  name: 'Anleitungen',
  components: { AnleitunsVerzeichnis, Intro }
}
</script>

<style scoped></style>
