// src/components/AnschaffungsRatgeber/AnschaffungsRatgeber.tsx
import { AnschaffungsElement } from "@/components/AnschaffungsRatgeber/AnschaffungsElement";
import { StaticImageData } from "next/image";

interface AnschaffungsRatgeberProps {
  intro: string;
  elements: Array<{ imgSrc: StaticImageData; title: string; text: string }>;
}

export const AnschaffungsRatgeber = ({
  intro,
  elements,
}: AnschaffungsRatgeberProps) => (
  <div className="container">
    <div className="row">
      <div className="col col-md-10 offset-md-1 mb-5">{intro}</div>
    </div>
    <div className="row">
      {elements.map((element) => (
        <div className="col col-sm-6 col-md-3 mb-4" key={element.title}>
          <AnschaffungsElement {...element} />
        </div>
      ))}
    </div>
  </div>
);

// pages/Tipps & Tricks/anschaffungsratgeber.vue
<template>
  <div>
    <Intro small>
      <h2 class="mb-5">Anschaffungsratgeber</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          Text für Galerien
        </b-col>
      </b-row>
    </Intro>
    <AnschaffungsratgeberComponent />
  </div>
</template>

<script>
import AnschaffungsratgeberComponent from '~/components/anschaffungsratgeber'
import Intro from '~/components/intro'

export default {
  name: 'Anschaffungsratgeber',
  components: { AnschaffungsratgeberComponent, Intro }
}
</script>

<style scoped></style>
