// pages/Tipps & Tricks/anleitungen/scutum.vue
<template>
  <div>
    <Intro small>
      <h2 class="mb-5">Bau eines Scutums</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          <p>
            Das Scutum war eine Schutzwaffe, der Körper wird damit sehr gut
            geschützt, es ist aber überliefert, dass mit dem Schild auch nach
            dem Gegner geschlagen wurde. Der rechteckige Shild ist wohl eins der
            markantesten Merkmale der Legionäre zur Kaiserzeit.
          </p>
          <p>
            Einen Schild zu bauen ist deutlich einfacher als es vielleicht
            scheint. In unserer Gruppe haben wir bereits einige Schilde selbst
            gebaut. Eine große Motivation ist, dass Schilde mit
            Messingeinfassung bei Feldschlachten verboten sind, da Stücke von
            dem Messing absplittern können. Wenn man anstelle eines
            Legionärsschildes einen Auxiliarschild machen will, kann man den
            Schritt des Biegens weg lassen und die Form auf die eines typischen
            Ovalschildes ändern.
          </p>
          <p>
            Eine Anleitung von Fabian.
          </p>
        </b-col>
      </b-row>
    </Intro>

    <Section title="Materialien">
      <h3 class="h4 mt-4">Benötigte Materialien</h3>
      <ul>
        <li>
          Schildbuckel (Messing oder Stahl). Messing ist leichter und sehr
          schön, aber so dünn, dass es nicht für Schaukampf zu empfehlen ist.
          Ich habe 33€ für meinen aus Stahl bezahlt. Der Buckel aus Stahl kam
          bei mir im Gegensatz zu dem aus Messing ohne Vorbiegung.
        </li>
        <li>
          Zwei Sperrholzplatten. Empfohlene Maße: 85cm breit, zwischen 105 und
          125 cm hoch. Die günstigeren Schilde, die man online kaufen kann haben
          106cm. Bei meiner Größe von 190cm finde ich die Länge von 120cm
          passender. Für einen stabilen Schild würde ich 4mm Dicke Spanplatten
          empfehlen (kann man sich z.B. bei Hornbach direkt zuschneiden lassen,
          wenn es schnell gehen soll). Das resultierende Gewicht ist durchaus
          vergleichbar mit den Schilden, die man kaufen kann. Wenn es besonders
          leichtgewichtig sein soll, kann man auch online 3mm dickes Sperrholz
          kaufen. Als Holz gibt es in der Dicke meist nur Pappel, was mir bis
          jetzt gute Dienste geleistet hat. Meist hat eine Seite mehr Maserung
          als die Andere und dabei auch einen Verlauf. Ich habe darauf geachtet,
          dass die Maserung von oben nach unten verläuft, um der Biegung zu
          helfen.
        </li>
        <li>
          Holzleim (Wasserfest). Ich habe Ponal in der 750ml Dose genommen und
          das Meiste davon verwendet.
        </li>
        <li>
          Leinen, genug um Vorder- und Rückseite des Schilds zu bedecken (also
          etwa 180cm oder mehr). Das günstigste Leinen kann man beim IKEA
          kaufen. Durch die grobe Struktur, die dann durch den Leim verhärtet
          wird, wird daraus eine recht raue Oberfläche. Vielleicht ist
          feinmaschigeres Leinen da also besser. Ich habe naturfarbenes Leinen
          für die Vorderseite und blaues Leinen für die Rückseite genommen.
          Durch den Leim dunkelt die Farbe noch nach.
        </li>
        <li>
          Rohaut (oder dünnes Messing). Die Länge muss für einmal um den Schild
          herum reichen. Rohaut lässt sich meterweise auf Mittelaltermärkten
          besorgen, günstiger ist es aber, wenn man einen Knochen aus Rohaut für
          Hunde aufweicht und verarbeitet. Beim Einweichen können minderwertige
          Kauknochen sich auflösen und man hat nur einen Faserbrei.
          Empfehlenswert ist
          <a
            target="_blank"
            href="https://www.dehner.de/produkte/dehner-riesenkauknochen-geknotet-kausnacks-X000531855/"
            >dieser Riesenkauknochen von Dehner</a
          >. Er reicht gut für ein Schild.
        </li>
        <li>
          Dickes Garn (ggf aus Leder oder aus Leinen). Benötigt werden
          schätzungsweise 6-12m (abhängig vom Abstand der Löcher, gewähltem
          Stich, …) (z.B. ein
          <a
            target="_blank"
            href="https://smile.amazon.de/gp/product/B0772VNBPY"
            >solches Ledernähgarn</a
          >, kann aber auch noch dicker sein)
        </li>
        <li>Dünne Nägel aus Messing oder Stahl, 2-3cm lang, etwa 100 stück</li>
        <li>Farben (Rot, Gelb und Schwarz).</li>
        <li>
          Holz für Verstrebungen auf der Rückseite (z.B. zwei Mal 1m * 2cm *
          5mm)
        </li>
        <li>
          Metallreststücke (dünner Stahl oder Messing, um daraus
          Unterlegscheiben herzustellen).
        </li>
        <li>
          Nieten (3mm Schaftdurchmesser). Die Länge sollte durch den Buckel,
          Schild und Verstrebung reichen. Man kann natürlich auch einfach selbst
          Nieten aus 3mm dickem Draht (Messing oder Stahl) herstellen
        </li>
      </ul>

      <h3 class="h4 mt-4">Benötigte Werkzeuge</h3>
      <p>
        Hammer, Feilen (insbesondere Holz), Säge, Bohrer, eine Dicke Nadel oder
        Ahle, Schraubstock, ggf. einen Amboss, Nietsetzer, ein scharfes Messer,
        Pinsel, feste Unterlage (zum darauf hämmern), eine wasserdichte Plane,
        Zirkel, Maßband, Spanngurte (>6), Holzklötzchen/-stangen zum Unterlegen,
        Biegevorrichtung, …
      </p>
      <h4 class="h5">Die Biegevorrichtung</h4>
      <p>
        An dieser Stelle vielleicht eine Erörterung zur Biegevorrichtung. Diese
        gibt offensichtlich die Biegung des späteren Schildes vor (auch wenn
        sich durch das Aushärten des drauf geleimten Leinens noch etwas daran
        ändern kann). Ein erster Versuch hat einen sehr leicht gebogenen Schild
        ergeben. Durch die zu geringe Breite war die Schutzfunktion stark
        beeinträchtigt. Die Praxis hat außerdem ergeben, dass es im Gedränge von
        Vorteil ist, wenn man sich in seinen Schild hinein igeln kann, sodass
        man auch von der Seite eine geringere Angriffsfläche bietet.
        Entsprechend habe ich die Maße noch einmal überarbeitet. Die aktuellen
        Maße kann man sich auf diesem
        <a
          target="_blank"
          href="https://www.arndt-bruenner.de/mathe/scripts/kreissehnen.htm"
          >Online Kreisrechner von Arndt Brünner</a
        >
        ansehen.
      </p>
      <ul>
        <li>Länge der Sehe (s): 55cm</li>
        <li>Kreisradius (r): 30cm</li>
        <li>Mittelpunktswinkel der Sehne (ɑ): 160°</li>
        <li>Höhe des kleinen Segments (a): 24cm</li>
      </ul>
    </Section>

    <Section title="Arbeitsschritte">
      <h3 class="h4 mt-4">1. Das Holz vorbereiten</h3>
      <ul>
        <li>Das Holz auf die gewünschten Maße bringen</li>
        <li>
          Durch die Biegung wird das vordere Stück Holz etwas schmaler als das
          hintere. Es lohnt sich, etwa 1 cm der Breite des hinteren Stück Holz
          weg zu nehmen, damit das Holz nach dem Biegen gleiche Ausmaße hat.
        </li>
        <li>
          Die Ecken mit dem Zirkel abmessen und als Konsequenz abschneiden,
          sodass eine Rundung von 5-10 cm entsteht. Ich empfehle 7cm aufwärts,
          damit die Rundung schön einfach mit Rohaut zu bespannen ist. Der
          Schnitt lässt sich mit einer scharfen Stichsäge gut schneiden.
        </li>
      </ul>

      <b-img-lazy
        class="mb-2"
        alt="Zugeschnittenes Holz für zwei Schilde"
        :src="require('assets/anleitungen/Scutum_IMG_3283.jpg')"
        fluid
      />

      <h3 class="h4 mt-4">2. Das Holz leimen</h3>
      <ul>
        <li>
          Das Holz wird für die Meisten zu unhandlich sein, um es in kochendes
          Wasser zu legen und danach zu formen. Ich habe aus der Plane mit
          einigen Steinen ein Becken geformt, die Platten darin mit Wasser
          bedeckt und über Nacht einweichen lassen.
        </li>
        <li>
          Ich habe zunächst alle Spanngurte ausgelegt, dann die Holzpatten
          beidseitig mit Leim bestrichen und leicht antrocknen lassen. Dann die
          äußere Platte mit der Vorderseite nach unten auf die Gurte legen. Die
          zweite Platte mittig darauf legen. Dann die Biegekonstruktion darauf.
          Die Spanngurte langsam nacheinander und in Schritten immer von einer
          Seite zur anderen (z.B. von oben nach unten) fester ziehen. Dabei noch
          Hölzer an den Kanten unter den Spanngurten anbringen, damit das Holz
          vom Schild nicht von den Gurten eingeschnitten und verbogen wird. Wenn
          man zu viel Leim aufgetragen hat, wird der natürlich raus gepresst,
          also empfiehlt es sich etwas unter zu legen.
        </li>
        <li>
          Das Ganze so für mehrere Tage aushärten lassen (oder eher eine Woche,
          dann ist man auf der sicheren Seite) und dann die Spanngurte lösen.
        </li>
      </ul>

      <b-img-lazy
        class="mb-2"
        alt="Holz beim Einweichen"
        :src="require('assets/anleitungen/Scutum_IMG_3288.jpg')"
        fluid
      />
      <b-img-lazy
        class="mb-2"
        alt="Ausgelegte Materialien"
        :src="require('assets/anleitungen/Scutum_IMG_3294.jpg')"
        fluid
      />
      <b-img-lazy
        class="mb-2"
        alt="Aufgespannter Schild (vorne)"
        :src="require('assets/anleitungen/Scutum_IMG_3295.jpg')"
        fluid
      />
      <b-img-lazy
        class="mb-2"
        alt="Aufgespannter Schild (hinten)"
        :src="require('assets/anleitungen/Scutum_IMG_3297.jpg')"
        fluid
      />

      <h3 class="h4 mt-4">3. Ein erster Handgriff</h3>
      <ul>
        <li>
          Den exakten Mittelpunkt des Schilds auf der Vorderseite auf der Längs-
          und Querachse aufzeichnen und von dort aus einen Kreis aufzeichnen,
          der marginal größer ist als das Loch des Schildbuckels. Jetzt muss
          entlang der Horizontalen des späteren Schilds jeweils eine Linie
          oberhalb und unterhalb der Mitte gezogen werden (1,5-2cm Abstand zur
          Mitte). Dieser Steg wird später noch zusätzlich verstärkt.
        </li>
        <li>
          Entlang der Linien ausschneiden (wahlweise auf der designierten
          unteren Hälfte nicht ganz der Linie folgen, sondern den Kreis unten zu
          einer Geraden abändern
        </li>
        <li>
          Die Oberseite sehr gründlich feilen, sodass der Schild angenehm am
          langen Arm zu halten ist. Das heißt, dass der Schild an dieser Stelle
          also dem Verlauf der Haut folgen sollte und nicht eine Rundung oder
          gar Kante haben sollte.
        </li>
      </ul>

      <h3 class="h4 mt-4">4. Zusätzliche Stabilität</h3>
      <ul>
        <li>
          Die Innenseite mit Leinen auskleiden. Etwas von dem Wasserfesten Ponal
          mit Wasser verdünnen und gut vermischen (das kann man machen, solange
          der Ponal nicht schon mal getrocknet ist). Dann das Leinen mit dem
          Leim fest kleben. Ich habe dazu die Oberfläche von der Mitte aus mit
          dem Leim eingerieben. Wenn der Leim angetrocknet ist vorsichtig das
          Leinen über dem Loch für den Griff strahlenförmig einschneiden und
          durch das Loch umklappen.
        </li>
        <li>
          Als nächstes kann man die Verstärkung für den Griff anbringen. Ähnlich
          wie für das Holz für den Schild selbst sollte man das Holz entweder
          kochen oder lange einweichen. Dann die Grundlage und das Holz anleimen
          und auf die Biegekonstruktion spannen und aushärten lassen.
          Wahrscheinlich wird es ein bisschen schwierig, das Holz auf die
          Konstruktion zu bewegen, da jede Schicht Leinen das Holz beim
          Aushärten ein Bisschen in eine Richtung verbiegt, da es sich zusammen
          zieht. Wer ganz auf Nummer sicher gehen will, kann so eine Verstärkung
          auch an der Ober und Unterkante des Schildes zusätzlich anbringen
          (dann aber mindestens 3, besser 5 cm Abstand zum Rand lassen). Für
          diese und alle weiteren Verstärkungen in den folgenden Schritten
          empfiehlt sich, die nach oben liegenden Ecken und Kanten vor der
          Montage abzurunden.
        </li>
        <li>
          Als nächstes diese Verstrebung und weitere in der senkrechten des
          Schilds (entweder eine mittig und durch den Griff unterbrochen oder
          zwei entlang der Außenkanten mit Abstand zum Rand) mit den kleinen
          Nägeln sichern. Diese Nägel verstärken den Leim sehr gut. Sie werden
          von innen genagelt und können auf der Außenseite einfach umgeschlagen
          werden.
        </li>
        <li>
          Als nächstes die Außenseite mit Leinen einkleiden und verleimen. Das
          verdeckt die umgeschlagenen Nägel. Wenn man die richtige Art Farbe
          hat, kann man den Leim statt mit Wasser mit der Farbe verdünnen. Das
          Leinen bekommt so schon die Grundfarbe und die Farbe wird wasserfest
          (Wenn man wasserfesten Leim verwendet)
        </li>
      </ul>
      <b-img-lazy
        class="mb-2"
        alt="Leinen und Verstrebungen auf der Innenseite"
        :src="require('assets/anleitungen/Scutum_IMG_3350.jpg')"
        fluid
      />
      <b-img-lazy
        class="mb-2"
        alt="Leinen auf der Außenseite"
        :src="require('assets/anleitungen/Scutum_IMG_3367.jpg')"
        fluid
      />

      <h3 class="h4 mt-4">5. Der Schildgriff</h3>
      <ul>
        <li>
          Auf der Außenseite ein weiteres Stück Holz anbringen und das ganze
          rund feilen, sodass es gut in der Hand liegt. Nach wunsch kann der
          Griff durch eine Lederumwicklung noch bequemer gemacht werden.
        </li>
        <li>
          Bei längerem Tragen wird der vorher gefeilte Übergang dennoch am
          Handgelenk einschneiden, sodass ein weiteres Polster notwendig werden
          wird. Entweder mehrere Lagen Leder oder eine Art Kissen direkt am
          Schild befestigt, oder aber eine dickere Ledermanschette, die man um
          den Arm trägt (diese sollte bis über den Handrücken reichen). Die
          Befestigung funktioniert entweder mit Kleber, kleinen Nägeln, oder
          indem man die Vernietung des Schildbuckels mit benutzt.
        </li>
      </ul>
      <b-img-lazy
        class="mb-2"
        alt="Detailansicht Schildgriff Innenseite"
        :src="require('assets/anleitungen/Scutum_IMG_3498.jpg')"
        fluid
      />

      <h3 class="h4 mt-4">6. Die Umrandung</h3>
      <ul>
        <li>
          Den Hundekauknochen in warmem bis heißen Wasser über mehrere Stunden
          (z.B. über Nacht) einweichen lassen. Dann in die einzelnen Stücke
          zerlegen
        </li>
        <li>
          Die Rohaut in etwa 4-6cm breite Streifen schneiden (breiter, wenn man
          an den Seiten durch das Biegen einen größeren Abstand zwischen den
          Enden der Holzplatten hat). Dann anfangen, die Rohaut um den Schild zu
          legen und mit den Nägeln fest zu nageln. Dabei erst den Nagel durch
          Haut und Holz schlagen, dann auf der Rückseite die Rohaut spannen, mit
          einer Zange neben dem Nagel drücken, sodass der Nagel die Haut
          durchsticht und dann den Nagel sauber umbiegen. Hat mit einer
          Rohrzange sehr gut funktioniert. Die unterschiedlichen Streifen habe
          ich mit Überlappung befestigt, sodass Wasser nach unten abfließen
          würde. Abschließend habe ich noch Nägel mittig in die verbleibenden
          Abstände von der anderen Seite genagelt. Dann habe ich die Rohaut
          wieder trocknen lassen, was ihr schon sehr viel Stabilität gibt.
        </li>
        <li>
          Als nächsten Schritt habe ich einmal um die Rohaut außen herum genäht,
          um sie an einigen Stellen (wie den Rundungen und Übergängen)
          zusätzlich anzupressen und insgesamt zu sichern. Dazu habe ich die
          Sattlernaht verwendet. Ich musste leider 3mm Löcher vorbohren, da
          sonst die Nadel mit dem Faden nicht durch das Loch ging. Mit 2mm
          Löchern sähe es vielleicht ein bisschen besser aus.
        </li>
        <li>
          Als zusätzlichen Schritt kann man die Naht nochmal mit Leim
          überziehen, wenn man auch wirklich auf Nummer Sicher gehen will.
        </li>
      </ul>

      <h3 class="h4 mt-4">7. Schild verzieren</h3>
      <ul>
        <li>
          Typische Verzierungen, die heute verwendet werden beispielsweise
          Blitze, Donnerkeile, Adlerflügel. Alternativ könnten auch die
          Wappentiere der Legion verwendet werden. (z.B.
          <a
            target="_blank"
            href="https://de.wikipedia.org/wiki/Datei:Capricon_legioXXII-retouched.jpg"
            >Capricorn</a
          >
          )
        </li>
      </ul>

      <h3 class="h4 mt-4">8. Schildbuckel anbringen</h3>
      <ul>
        <li>
          Die meisten Buckel haben vier Löcher in den Ecken vorgebohrt. Man kann
          noch zusätzliche Löcher in der Mitte bohren. Damit lässt sich die
          Querverstrebung auf der Rückseite mit fest nieten, was zusätzliche
          Stabilität gibt.
        </li>
        <li>
          Vermutlich muss als nächstes die Biegung der Basis an die des Schildes
          angepasst werden
        </li>
        <li>
          Damit das Holz sich nieten lässt, braucht man unbedingt
          Unterlegscheiben und muss den Kopf der Niete sehr vorsichtig pilzen,
          bevor der Schaft sich verbiegt und nicht hält. Alternativ kann man die
          Niete auch umhämmern, was auch hält – nur nicht so schön aussieht (Das
          ist auf der Innenseite aber eher egal)
        </li>
      </ul>

      <b-img-lazy
        class="mb-2"
        alt="Schild mit Buckel (Die Umrandung ist auf dem Bild noch nicht fertig genäht)"
        :src="require('assets/anleitungen/Scutum_IMG_3389.jpg')"
        fluid
      />
    </Section>
  </div>
</template>

<script>
import Intro from '~/components/intro'
import Section from '~/components/section'

export default {
  name: 'Scutum',
  components: { Intro, Section }
}
</script>

<style scoped></style>

// src/app/anleitungen/scutum/page.tsx
import { PageIntro } from "@/components/PageIntro/PageIntro";
import { Section } from "@/components/Section/Section";
import Scutum1 from "@/images/anleitungen/Scutum_IMG_3283.jpg";
import Scutum2 from "@/images/anleitungen/Scutum_IMG_3288.jpg";
import Scutum3 from "@/images/anleitungen/Scutum_IMG_3294.jpg";
import Scutum4 from "@/images/anleitungen/Scutum_IMG_3295.jpg";
import Scutum5 from "@/images/anleitungen/Scutum_IMG_3297.jpg";
import Scutum6 from "@/images/anleitungen/Scutum_IMG_3350.jpg";
import Scutum7 from "@/images/anleitungen/Scutum_IMG_3367.jpg";
import Scutum8 from "@/images/anleitungen/Scutum_IMG_3498.jpg";
import Scutum9 from "@/images/anleitungen/Scutum_IMG_3389.jpg";
import { AnleitungsBild } from "@/components/AnleitungsBild/AnleitungsBild";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "IG Romanum - Anleitung Scutum",
  description:
    "Schritt für Schritt Anleitung zum Bau eines römischen Legionärsschilds (Scutum) mit modernen Materialien.",
  keywords: [
    "Scutum",
    "Legionärsschild",
    "Römisches Reenactment",
    "Schildbau",
    "Anleitung",
    "IG Romanum",
    "Basteln",
    "Ausrüstung",
  ],
  authors: [{ name: "IG Romanum" }],
  openGraph: {
    title: "IG Romanum - Anleitung Scutum",
    description:
      "Schritt für Schritt Anleitung zum Bau eines römischen Legionärsschilds (Scutum) mit modernen Materialien.",
    images: ["/images/banner.jpg"],
    type: "article",
    url: "https://www.ig-romanum.de/anleitungen/scutum",
  },
  twitter: {
    card: "summary_large_image",
    title: "IG Romanum - Anleitung Scutum",
    description:
      "Schritt für Schritt Anleitung zum Bau eines römischen Legionärsschilds (Scutum) mit modernen Materialien.",
    images: ["/images/banner.jpg"],
  },
  robots: "index, follow",
  alternates: {
    canonical: "https://www.ig-romanum.de/anleitungen/scutum",
  },
};

const ScutumPage = () => (
  <>
    <PageIntro
      img={`/AnleitungsBilder/scutum.jpg`}
      imgAlt="Zeichnerische Darstellung eines römischen Scutums"
    >
      <h2 className="mb-5">Bau eines Scutums</h2>
      <h3 className="mb-4">Wie man einen römischen Schild selbst bauen kann</h3>
      <div className="row mb-4">
        <div className="col-md-10 offset-md-1">
          <p>
            Das Scutum war eine Schutzwaffe, der Körper wird damit sehr gut
            geschützt, es ist aber überliefert, dass mit dem Schild auch nach
            dem Gegner geschlagen wurde. Der rechteckige Shild ist wohl eins der
            markantesten Merkmale der Legionäre zur Kaiserzeit.
          </p>
          <p>
            Einen Schild zu bauen ist deutlich einfacher als es vielleicht
            scheint. In unserer Gruppe haben wir bereits einige Schilde selbst
            gebaut. Eine große Motivation ist, dass Schilde mit
            Messingeinfassung bei Feldschlachten verboten sind, da Stücke von
            dem Messing absplittern können. Wenn man anstelle eines
            Legionärsschildes einen Auxiliarschild machen will, kann man den
            Schritt des Biegens weg lassen und die Form auf die eines typischen
            Ovalschildes ändern. Das selbe gilt für einen flachen Rundschild
            oder abgerundeten Tropfenschild, wie er von der römischen Kavallerie
            verwendet wurde.
          </p>
          <p>Eine Anleitung von Fabian.</p>
        </div>
      </div>
    </PageIntro>

    <Section title="Materialien">
      <h3 className="h4 mt-4">Benötigte Materialien</h3>
      <ul>
        <li>
          Schildbuckel (Messing oder Stahl). Messing ist leichter und sehr
          schön, aber so dünn, dass es nicht für Schaukampf zu empfehlen ist.
          Ich habe 33€ für meinen aus Stahl bezahlt. Der Buckel aus Stahl kam
          bei mir im Gegensatz zu dem aus Messing ohne Vorbiegung.
        </li>
        <li>
          Zwei Sperrholzplatten. Empfohlene Maße: 85cm breit, zwischen 105 und
          125 cm hoch. Die günstigeren Schilde, die man online kaufen kann haben
          106cm. Bei meiner Größe von 190cm finde ich die Länge von 120cm
          passender. Für einen stabilen Schild würde ich 4mm Dicke Spanplatten
          empfehlen (kann man sich z.B. bei Hornbach direkt zuschneiden lassen,
          wenn es schnell gehen soll). Das resultierende Gewicht ist durchaus
          vergleichbar mit den Schilden, die man kaufen kann. Wenn es besonders
          leichtgewichtig sein soll, kann man auch online 3mm dickes Sperrholz
          kaufen. Als Holz gibt es in der Dicke meist nur Pappel, was mir bis
          jetzt gute Dienste geleistet hat. Meist hat eine Seite mehr Maserung
          als die Andere und dabei auch einen Verlauf. Ich habe darauf geachtet,
          dass die Maserung von oben nach unten verläuft, um der Biegung zu
          helfen.
        </li>
        <li>
          Holzleim (Wasserfest). Ich habe Ponal in der 750ml Dose genommen und
          das Meiste davon verwendet.
        </li>
        <li>
          Leinen, genug um Vorder- und Rückseite des Schilds zu bedecken (also
          etwa 180cm oder mehr). Das günstigste Leinen kann man beim IKEA
          kaufen. Durch die grobe Struktur, die dann durch den Leim verhärtet
          wird, wird daraus eine recht raue Oberfläche. Vielleicht ist
          feinmaschigeres Leinen da also besser. Ich habe naturfarbenes Leinen
          für die Vorderseite und blaues Leinen für die Rückseite genommen.
          Durch den Leim dunkelt die Farbe noch nach.
        </li>
        <li>
          Rohaut (oder dünnes Messing). Die Länge muss für einmal um den Schild
          herum reichen. Rohaut lässt sich meterweise auf Mittelaltermärkten
          besorgen, günstiger ist es aber, wenn man einen Knochen aus Rohaut für
          Hunde aufweicht und verarbeitet. Beim Einweichen können minderwertige
          Kauknochen sich auflösen und man hat nur einen Faserbrei.
          Empfehlenswert ist{" "}
          <a
            target="_blank"
            href="https://www.dehner.de/produkte/dehner-riesenkauknochen-geknotet-kausnacks-X000531855/"
          >
            dieser Riesenkauknochen von Dehner
          </a>
          . Er reicht gut für ein Schild.
        </li>
        <li>
          Dickes Garn (ggf aus Leder oder aus Leinen). Benötigt werden
          schätzungsweise 6-12m (abhängig vom Abstand der Löcher, gewähltem
          Stich, …) (z.B. ein{" "}
          <a
            target="_blank"
            href="https://smile.amazon.de/gp/product/B0772VNBPY"
          >
            solches Ledernähgarn
          </a>
          , kann aber auch noch dicker sein)
        </li>
        <li>Dünne Nägel aus Messing oder Stahl, 2-3cm lang, etwa 100 stück</li>
        <li>Farben (Rot, Gelb und Schwarz).</li>
        <li>
          Holz für Verstrebungen auf der Rückseite (z.B. zwei Mal 1m * 2cm *
          5mm)
        </li>
        <li>
          Metallreststücke (dünner Stahl oder Messing, um daraus
          Unterlegscheiben herzustellen).
        </li>
        <li>
          Nieten (3mm Schaftdurchmesser). Die Länge sollte durch den Buckel,
          Schild und Verstrebung reichen. Man kann natürlich auch einfach selbst
          Nieten aus 3mm dickem Draht (Messing oder Stahl) herstellen
        </li>
      </ul>

      <h3 className="h4 mt-4">Benötigte Werkzeuge</h3>
      <p>
        Hammer, Feilen (insbesondere Holz), Säge, Bohrer, eine Dicke Nadel oder
        Ahle, Schraubstock, ggf. einen Amboss, Nietsetzer, ein scharfes Messer,
        Pinsel, feste Unterlage (zum darauf hämmern), eine wasserdichte Plane,
        Zirkel, Maßband, Spanngurte (&gt;6), Holzklötzchen/-stangen zum
        Unterlegen, Biegevorrichtung, …
      </p>
      <h4 className="h5">Die Biegevorrichtung</h4>
      <p>
        An dieser Stelle vielleicht eine Erörterung zur Biegevorrichtung. Diese
        gibt offensichtlich die Biegung des späteren Schildes vor (auch wenn
        sich durch das Aushärten des drauf geleimten Leinens noch etwas daran
        ändern kann). Ein erster Versuch hat einen sehr leicht gebogenen Schild
        ergeben. Durch die zu geringe Breite war die Schutzfunktion stark
        beeinträchtigt. Die Praxis hat außerdem ergeben, dass es im Gedränge von
        Vorteil ist, wenn man sich in seinen Schild hinein igeln kann, sodass
        man auch von der Seite eine geringere Angriffsfläche bietet.
        Entsprechend habe ich die Maße noch einmal überarbeitet. Die aktuellen
        Maße kann man sich auf diesem{" "}
        <a
          target="_blank"
          href="https://www.arndt-bruenner.de/mathe/scripts/kreissehnen.htm"
        >
          Online Kreisrechner von Arndt Brünner
        </a>{" "}
        ansehen.
      </p>
      <ul>
        <li>Länge der Sehe (s): 55cm</li>
        <li>Kreisradius (r): 30cm</li>
        <li>Mittelpunktswinkel der Sehne (ɑ): 160°</li>
        <li>Höhe des kleinen Segments (a): 24cm</li>
      </ul>
    </Section>

    <Section title="Arbeitsschritte">
      <h3 className="h4 mt-4">1. Das Holz vorbereiten</h3>
      <ul>
        <li>Das Holz auf die gewünschten Maße bringen</li>
        <li>
          Durch die Biegung wird das vordere Stück Holz etwas schmaler als das
          hintere. Es lohnt sich, etwa 1 cm der Breite des hinteren Stück Holz
          weg zu nehmen, damit das Holz nach dem Biegen gleiche Ausmaße hat.
        </li>
        <li>
          Die Ecken mit dem Zirkel abmessen und als Konsequenz abschneiden,
          sodass eine Rundung von 5-10 cm entsteht. Ich empfehle 7cm aufwärts,
          damit die Rundung schön einfach mit Rohaut zu bespannen ist. Der
          Schnitt lässt sich mit einer scharfen Stichsäge gut schneiden.
        </li>
      </ul>

      <AnleitungsBild
        src={Scutum1}
        alt="Zugeschnittenes Holz für zwei Schilde"
      />

      <h3 className="h4 mt-4">2. Das Holz leimen</h3>
      <ul>
        <li>
          Das Holz wird für die Meisten zu unhandlich sein, um es in kochendes
          Wasser zu legen und danach zu formen. Ich habe aus der Plane mit
          einigen Steinen ein Becken geformt, die Platten darin mit Wasser
          bedeckt und über Nacht einweichen lassen.
        </li>
        <li>
          Ich habe zunächst alle Spanngurte ausgelegt, dann die Holzpatten
          beidseitig mit Leim bestrichen und leicht antrocknen lassen. Dann die
          äußere Platte mit der Vorderseite nach unten auf die Gurte legen. Die
          zweite Platte mittig darauf legen. Dann die Biegekonstruktion darauf.
          Die Spanngurte langsam nacheinander und in Schritten immer von einer
          Seite zur anderen (z.B. von oben nach unten) fester ziehen. Dabei noch
          Hölzer an den Kanten unter den Spanngurten anbringen, damit das Holz
          vom Schild nicht von den Gurten eingeschnitten und verbogen wird. Wenn
          man zu viel Leim aufgetragen hat, wird der natürlich raus gepresst,
          also empfiehlt es sich etwas unter zu legen.
        </li>
        <li>
          Das Ganze so für mehrere Tage aushärten lassen (oder eher eine Woche,
          dann ist man auf der sicheren Seite) und dann die Spanngurte lösen.
        </li>
      </ul>

      <AnleitungsBild src={Scutum2} alt="Holz beim Einweichen" />
      <AnleitungsBild src={Scutum3} alt="Ausgelegte Materialien" />
      <AnleitungsBild src={Scutum4} alt="Aufgespannter Schild (vorne)" />
      <AnleitungsBild src={Scutum5} alt="Aufgespannter Schild (hinten)" />

      <h3 className="h4 mt-4">3. Ein erster Handgriff</h3>
      <ul>
        <li>
          Den exakten Mittelpunkt des Schilds auf der Vorderseite auf der Längs-
          und Querachse aufzeichnen und von dort aus einen Kreis aufzeichnen,
          der marginal größer ist als das Loch des Schildbuckels. Jetzt muss
          entlang der Horizontalen des späteren Schilds jeweils eine Linie
          oberhalb und unterhalb der Mitte gezogen werden (1,5-2cm Abstand zur
          Mitte). Dieser Steg wird später noch zusätzlich verstärkt.
        </li>
        <li>
          Entlang der Linien ausschneiden (wahlweise auf der designierten
          unteren Hälfte nicht ganz der Linie folgen, sondern den Kreis unten zu
          einer Geraden abändern
        </li>
        <li>
          Die Oberseite sehr gründlich feilen, sodass der Schild angenehm am
          langen Arm zu halten ist. Das heißt, dass der Schild an dieser Stelle
          also dem Verlauf der Haut folgen sollte und nicht eine Rundung oder
          gar Kante haben sollte.
        </li>
      </ul>

      <h3 className="h4 mt-4">4. Zusätzliche Stabilität</h3>
      <ul>
        <li>
          Die Innenseite mit Leinen auskleiden. Etwas von dem Wasserfesten Ponal
          mit Wasser verdünnen und gut vermischen (das kann man machen, solange
          der Ponal nicht schon mal getrocknet ist). Dann das Leinen mit dem
          Leim fest kleben. Ich habe dazu die Oberfläche von der Mitte aus mit
          dem Leim eingerieben. Wenn der Leim angetrocknet ist vorsichtig das
          Leinen über dem Loch für den Griff strahlenförmig einschneiden und
          durch das Loch umklappen.
        </li>
        <li>
          Als nächstes kann man die Verstärkung für den Griff anbringen. Ähnlich
          wie für das Holz für den Schild selbst sollte man das Holz entweder
          kochen oder lange einweichen. Dann die Grundlage und das Holz anleimen
          und auf die Biegekonstruktion spannen und aushärten lassen.
          Wahrscheinlich wird es ein bisschen schwierig, das Holz auf die
          Konstruktion zu bewegen, da jede Schicht Leinen das Holz beim
          Aushärten ein Bisschen in eine Richtung verbiegt, da es sich zusammen
          zieht. Wer ganz auf Nummer sicher gehen will, kann so eine Verstärkung
          auch an der Ober und Unterkante des Schildes zusätzlich anbringen
          (dann aber mindestens 3, besser 5 cm Abstand zum Rand lassen). Für
          diese und alle weiteren Verstärkungen in den folgenden Schritten
          empfiehlt sich, die nach oben liegenden Ecken und Kanten vor der
          Montage abzurunden.
        </li>
        <li>
          Als nächstes diese Verstrebung und weitere in der senkrechten des
          Schilds (entweder eine mittig und durch den Griff unterbrochen oder
          zwei entlang der Außenkanten mit Abstand zum Rand) mit den kleinen
          Nägeln sichern. Diese Nägel verstärken den Leim sehr gut. Sie werden
          von innen genagelt und können auf der Außenseite einfach umgeschlagen
          werden.
        </li>
        <li>
          Als nächstes die Außenseite mit Leinen einkleiden und verleimen. Das
          verdeckt die umgeschlagenen Nägel. Wenn man die richtige Art Farbe
          hat, kann man den Leim statt mit Wasser mit der Farbe verdünnen. Das
          Leinen bekommt so schon die Grundfarbe und die Farbe wird wasserfest
          (Wenn man wasserfesten Leim verwendet)
        </li>
      </ul>
      <AnleitungsBild
        src={Scutum6}
        alt="Leinen und Verstrebungen auf der Innenseite"
      />
      <AnleitungsBild src={Scutum7} alt="Leinen auf der Außenseite" />

      <h3 className="h4 mt-4">5. Der Schildgriff</h3>
      <ul>
        <li>
          Auf der Außenseite ein weiteres Stück Holz anbringen und das ganze
          rund feilen, sodass es gut in der Hand liegt. Nach wunsch kann der
          Griff durch eine Lederumwicklung noch bequemer gemacht werden.
        </li>
        <li>
          Bei längerem Tragen wird der vorher gefeilte Übergang dennoch am
          Handgelenk einschneiden, sodass ein weiteres Polster notwendig werden
          wird. Entweder mehrere Lagen Leder oder eine Art Kissen direkt am
          Schild befestigt, oder aber eine dickere Ledermanschette, die man um
          den Arm trägt (diese sollte bis über den Handrücken reichen). Die
          Befestigung funktioniert entweder mit Kleber, kleinen Nägeln, oder
          indem man die Vernietung des Schildbuckels mit benutzt.
        </li>
      </ul>
      <AnleitungsBild
        src={Scutum8}
        alt="Detailansicht Schildgriff Innenseite"
      />

      <h3 className="h4 mt-4">6. Die Umrandung</h3>
      <ul>
        <li>
          Den Hundekauknochen in warmem bis heißen Wasser über mehrere Stunden
          (z.B. über Nacht) einweichen lassen. Dann in die einzelnen Stücke
          zerlegen
        </li>
        <li>
          Die Rohaut in etwa 4-6cm breite Streifen schneiden (breiter, wenn man
          an den Seiten durch das Biegen einen größeren Abstand zwischen den
          Enden der Holzplatten hat). Dann anfangen, die Rohaut um den Schild zu
          legen und mit den Nägeln fest zu nageln. Dabei erst den Nagel durch
          Haut und Holz schlagen, dann auf der Rückseite die Rohaut spannen, mit
          einer Zange neben dem Nagel drücken, sodass der Nagel die Haut
          durchsticht und dann den Nagel sauber umbiegen. Hat mit einer
          Rohrzange sehr gut funktioniert. Die unterschiedlichen Streifen habe
          ich mit Überlappung befestigt, sodass Wasser nach unten abfließen
          würde. Abschließend habe ich noch Nägel mittig in die verbleibenden
          Abstände von der anderen Seite genagelt. Dann habe ich die Rohaut
          wieder trocknen lassen, was ihr schon sehr viel Stabilität gibt.
        </li>
        <li>
          Als nächsten Schritt habe ich einmal um die Rohaut außen herum genäht,
          um sie an einigen Stellen (wie den Rundungen und Übergängen)
          zusätzlich anzupressen und insgesamt zu sichern. Dazu habe ich die
          Sattlernaht verwendet. Ich musste leider 3mm Löcher vorbohren, da
          sonst die Nadel mit dem Faden nicht durch das Loch ging. Mit 2mm
          Löchern sähe es vielleicht ein bisschen besser aus.
        </li>
        <li>
          Als zusätzlichen Schritt kann man die Naht nochmal mit Leim
          überziehen, wenn man auch wirklich auf Nummer Sicher gehen will.
        </li>
      </ul>

      <h3 className="h4 mt-4">7. Schild verzieren</h3>
      <ul>
        <li>
          Typische Verzierungen, die heute verwendet werden beispielsweise
          Blitze, Donnerkeile, Adlerflügel. Alternativ könnten auch die
          Wappentiere der Legion verwendet werden. (z.B.{" "}
          <a
            target="_blank"
            href="https://de.wikipedia.org/wiki/Datei:Capricon_legioXXII-retouched.jpg"
          >
            Capricorn
          </a>
          )
        </li>
      </ul>

      <h3 className="h4 mt-4">8. Schildbuckel anbringen</h3>
      <ul>
        <li>
          Die meisten Buckel haben vier Löcher in den Ecken vorgebohrt. Man kann
          noch zusätzliche Löcher in der Mitte bohren. Damit lässt sich die
          Querverstrebung auf der Rückseite mit fest nieten, was zusätzliche
          Stabilität gibt.
        </li>
        <li>
          Vermutlich muss als nächstes die Biegung der Basis an die des Schildes
          angepasst werden
        </li>
        <li>
          Damit das Holz sich nieten lässt, braucht man unbedingt
          Unterlegscheiben und muss den Kopf der Niete sehr vorsichtig pilzen,
          bevor der Schaft sich verbiegt und nicht hält. Alternativ kann man die
          Niete auch umhämmern, was auch hält – nur nicht so schön aussieht (Das
          ist auf der Innenseite aber eher egal)
        </li>
      </ul>

      <AnleitungsBild
        src={Scutum9}
        alt="Schild mit Buckel (Die Umrandung ist auf dem Bild noch nicht fertig genäht)"
      />
    </Section>
  </>
);

export default ScutumPage;
