// components/ButtonWrapper.vue
<template>
  <b-row :class="classString">
    <b-col offset-md="3" md="6">
      <b-button variant="primary" size="lg" :to="to" block
        ><slot></slot
      ></b-button>
    </b-col>
  </b-row>
</template>

<script>
export default {
  name: 'ButtonWrapper',
  props: {
    lastItem: {
      type: Boolean,
      default: false,
      required: false
    },
    to: {
      type: String,
      required: true
    }
  },
  computed: {
    classString() {
      return this.lastItem ? '' : 'mb-4'
    }
  }
}
</script>

// src/components/ButtonWrapper.tsx
import { LinkButton } from "@/components/Button/LinkButton";
import { PropsWithChildren } from "react";

interface ButtonWrapperProps extends PropsWithChildren {
  to: string;
  lastItem?: boolean;
  className?: string;
}

export const ButtonWrapper = ({
  to,
  lastItem,
  children,
  className,
}: ButtonWrapperProps) => (
  <div className={`row ${lastItem ? "mb-4" : ""} ${className}`}>
    <div className="col col-md-6 offset-md-3">
      <LinkButton to={to}>{children}</LinkButton>
    </div>
  </div>
);
