// src/app/kontakt/page.tsx
import { PageIntro } from "@/components/PageIntro/PageIntro";
import Banner from "@/images/banner/banner_kontakt2.jpg";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "IG Romanum - Kontakt",
  description: "Kontaktseite der IG Imperium Romanum",
  keywords: [
    "Kontakt",
    "IG Romanum",
    "Römer",
    "Reenactment",
    "Legionär",
    "Auxiliar",
    "Geschichte",
    "Living History",
  ],
  authors: [{ name: "IG Romanum" }],
  openGraph: {
    title: "IG Romanum - Kontakt",
    description: "Kontaktseite der IG Imperium Romanum",
    images: ["/images/banner/banner_kontakt2.jpg"],
    type: "website",
    url: "https://www.ig-romanum.de/kontakt",
  },
  twitter: {
    card: "summary_large_image",
    title: "IG Romanum - Kontakt",
    description: "Kontaktseite der IG Imperium Romanum",
    images: ["/images/banner/banner_kontakt2.jpg"],
  },
  robots: "index, follow",
  alternates: {
    canonical: "https://www.ig-romanum.de/kontakt",
  },
};

const Kontakt = () => (
  <>
    <PageIntro
      img={Banner}
      imgAlt="Die Mitglieder der IG Romanum präsentieren sich vor ihrem Lager"
    >
      <h2 className="mb-5">Kontakt</h2>
      <div className="row mb-4">
        <div className="col col-md-10 offset-md-1">
          Du hast Fragen zu unserer Truppe oder den vielen Anleitungen? Du hast
          Interesse an der Darstellung eines antiken Römers oder möchtest sogar
          mal bei einem Event bei unserer Gruppe reinschnuppern? Dann melde Dich
          einfach bei uns, wir heißen jeden herzlich willkommen!
        </div>

        <div className="col col-md-10 offset-md-1">
          Du organisierst ein römisches Event, sei es im Rahmen eines Marktes,
          in einem Museum oder an einem historischen Ort? Schreib uns gerne an
          und wenn es bei uns zeitlich und räumlich passt, können wir gerne
          zusammenarbeiten!
        </div>
      </div>
      <div className="d-flex justify-content-around flex-wrap">
        <a href="mailto:ig-romanum@web.de" className="text-center">
          IG-Romanum@web.de
        </a>
        <a
          href="https://www.instagram.com/ig_imperiumromanum/"
          target="_blank"
          className="text-center"
        >
          IG Romanum auf Instagram
        </a>
        <a
          href="https://www.facebook.com/people/IG-Imperium-Romanum/100091977772885/"
          target="_blank"
          className="text-center"
        >
          IG Romanum auf Facebook
        </a>
      </div>
    </PageIntro>
  </>
);

export default Kontakt;

// pages/kontakt.vue
<template>
  <div>
    <Intro small :image-url="require('~/assets/banner/banner_kontakt2.jpg')">
      <h2 class="mb-5">Kontakt</h2>
      <b-row class="mb-4">
        <b-col offset-md="1" md="10">
          Du hast Fragen zu unserer Truppe oder den vielen Anleitungen? Du hast
          Interesse an der Darstellung eines antiken Römers oder möchtest sogar
          mal bei einem Event bei unserer Gruppe reinschnuppern? Dann melde Dich
          einfach bei uns, wir heißen jeden herzlich willkommen!
        </b-col>
      </b-row>
      <a href="mailto:ig-romanum@web.de" class="text-center"
        >IG-Romanum@web.de</a
      >
    </Intro>
  </div>
</template>

<script>
import Intro from '~/components/intro'

export default {
  name: 'KontaktVue',
  components: { Intro },
  head() {
    return {
      title: 'Kontakt',
      meta: [
        {
          hid: 'ogTitle',
          property: 'og:title',
          content: 'Nimm Kontakt zur IG Romanum auf!'
        }
      ]
    }
  }
}
</script>
